
name: 'Star_Wars'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  Star_Wars:
    staging:
      +materialized: view
      +group: star_wars
    silver:
      +materialized: table
      +group: star_wars
    gold:
      +materialized: view
      +group: star_wars
