models:
  - name: characters
    description: Charatecters from all movies
    columns:
      - name: character_id
        tests:
          - unique
          - not_null
  - name: films
    description: Details of first six star wars films
    columns:
      - name: film_id
        tests:
          - unique
          - not_null
  - name: planets
    description: Planets featured in Star Wars universe
    columns:
      - name: planet_id
        tests:
          - unique
          - not_null
  - name: bridge_film_characters
  - name: bridge_film_planets
  - name: bridge_film_vehicles