sources:
  - name: Dagobah
    database: Dagobah
    schema: dbo
    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 7, period: day}
    loaded_at_field: '[result.properties.edited]'
    tables:
      - name: People
        description: People/Character data from Swapi
      - name: Films
        description: Film data from Swapi
      - name: Planets
        description: Planet data from Swapi
      - name: Vehicles
        description: Vehicle data from Swapi