sources:
  - name: Dagobah
    description: Dagobah Lakehouse, it is. In the murky depths of Fabric Lakehouse, stored Star Wars API data is. A repository of knowledge, it serves, strong with the Force of information. Terrain, climate, population, and notable residents, preserved here are. A hub for exploration and learning, Dagobah Lakehouse has become.
    database: Dagobah
    schema: dbo
    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 7, period: day}
    loaded_at_field: '[result.properties.edited]'
    tables:
      - name: People
        description: People/Character data from Swapi
      - name: Films
        description: Film data from Swapi
      - name: Planets
        description: Planet data from Swapi
      - name: Vehicles
        description: Vehicle data from Swapi