sources:
  - name: Dagobah
    database: Dagobah
    schema: dbo
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: edited
    tables:
      - name: People
      - name: Films
      - name: Planets
      - name: Vehicles
